add only tunnel creating and direct connection

diff --git a/anyshell b/anyshell
--- a/anyshell
+++ b/anyshell
@@ -6,6 +6,16 @@ Server_public_IP=$(nslookup $Server_dns | sed -n 's/Address: //p')
 
 systemctl is-enabled sshd.service >/dev/null 2>&1 && Host_sshd=1 || Host_sshd=0
 
+trap ctrl_c INT
+function ctrl_c() {
+    echo "Stopping anyshell..."
+    if [ -S $HOME/.anyshell/socket ]; then
+        ssh -S ~/.anyshell/socket -O exit localhost
+    fi
+    sed -i '4s/.*/0/' ~/.anyshell/hosts/$Host_name
+    scp -P 41999 -i ~/.ssh/anyshell-key ~/.anyshell/hosts/$Host_name $Server_user@$Server_dns:/home/$Server_user/.anyshell/hosts/ >/dev/null
+    exit 1
+}
 update () {
     sed -i '1s/.*/1/' ~/.anyshell/status/$HOSTNAME
     time=$(echo "$(date +%y)$(date +%m)$(date +%d):$(date +%H)$(date +%M)$(date +%S)")
@@ -22,6 +32,22 @@ update () {
 }
 
 if [ "$1" == "connect" ]; then
+    pre='^[0-9]+$'
+    if [ "$2" == "-w" ]; then
+        wakeonlan=1
+    elif [[ $2 =~ $pre ]]; then
+        Host_number=$2
+        choose=1
+    elif [ "$2" == "-n" ]; then
+        noconnection=1
+    fi
+    if [ "$3" == "-n" ]; then
+        noconnection=1
+    elif [[ $3 =~ $pre ]]; then
+        Host_number=$2
+        choose=1
+    fi
+
     if [ -d ~/.anyshell/hosts ]; then rm -r ~/.anyshell/hosts; fi
     if [ -d ~/.anyshell/status ]; then rm -r ~/.anyshell/status; fi
     scp -P 41999 -i ~/.ssh/anyshell-key -r $Server_user@$Server_dns:/home/$Server_user/.anyshell/status ~/.anyshell/ >/dev/null
@@ -29,16 +55,17 @@ if [ "$1" == "connect" ]; then
     if [[ $EUID == 0 ]]; then chmod a+wrx -R ~/.anyshell/hosts ~/.anyshell/status; fi
     Client_public_IP=$(curl -s ifconfig.me | grep -o -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
 
-    echo -e "\nWhich Host do you want to connect to?\n"
-    i=1
-    for file in ~/.anyshell/hosts/*; do
-        name=$(basename $file) 
-        echo "$i:  $name"
-        i=$(( $i + 1 ))
-    done
-    echo ""
-
-    read -p "Number:" Host_number
+    if ! [ "$choose" == "1" ]; then
+        echo -e "\nWhich Host do you want to connect to?\n"
+        i=1
+        for file in ~/.anyshell/hosts/*; do
+            name=$(basename $file) 
+            echo "$i:  $name"
+            i=$(( $i + 1 ))
+        done
+        echo ""
+        read -p "Number:" Host_number
+    fi
 
     echo ""
     online="online:" 
@@ -62,52 +89,90 @@ if [ "$1" == "connect" ]; then
     sed -i '4s/.*/1/' ~/.anyshell/hosts/$Host_name
     scp -P 41999 -i ~/.ssh/anyshell-key ~/.anyshell/hosts/$Host_name $Server_user@$Server_dns:/home/$Server_user/.anyshell/hosts/ >/dev/null
 
-    if [[ "$Host_public_IP" == "$Client_public_IP" ]]; then
-        echo -e "\nTarget is on same network, connecting localy:"
-        for (( i = 0; i <= 10 ; i++ )); do
-            {
-                ssh $Host_user@$Host_local_IP -q && break 
-            } || { 
-                echo -n "."
-                if [ $i == 10 ]; then
-                    echo -e "\nCould not create a connection, client might be offline"
-                fi
-                sleep 1
-            }
-        done
-    elif [ "$Client_public_IP" == "$Server_public_IP" ]; then
-        echo -e "\n Server is on same network, connecting localy:"
-        lsof -ti:41000 | xargs kill -9 &> /dev/null
-        ssh -f -N -T -M -S ~/.anyshell/socket $Server_user@$Server_local_IP -p 41999 -i ~/.ssh/anyshell-key -L 41000:localhost:$Host_port
-        for (( i = 0; i <= 10 ; i++ )); do
-            {
-                ssh $Host_user@localhost -q -p 41000 && break 
-            } || { 
-                echo -n "."
-                if [ $i == 10 ]; then
-                    echo -e "\nCould not create a connection, client might be offline"
-                fi
-                sleep 1
-            }
-        done
-        ssh -S ~/.anyshell/socket -O exit localhost
+    if ! [ "$noconnection" == "1" ]; then
+        if [[ "$Host_public_IP" == "$Client_public_IP" ]]; then
+            echo -e "\nTarget is on same network, connecting localy:"
+            for (( i = 0; i <= 10 ; i++ )); do
+                {
+                    ssh $Host_user@$Host_local_IP -q && break 
+                } || { 
+                    echo -n "."
+                    if [ $i == 10 ]; then
+                        echo -e "\nCould not create a connection, client might be offline"
+                    fi
+                    sleep 1
+                }
+            done
+        elif [ "$Client_public_IP" == "$Server_public_IP" ]; then
+            echo -e "\n Server is on same network, connecting localy:"
+            lsof -ti:41000 | xargs kill -9 &> /dev/null
+            ssh -f -N -T -M -S ~/.anyshell/socket $Server_user@$Server_local_IP -p 41999 -i ~/.ssh/anyshell-key -L 41000:localhost:$Host_port
+            for (( i = 0; i <= 10 ; i++ )); do
+                {
+                    ssh $Host_user@localhost -q -p 41000 && break 
+                } || { 
+                    echo -n "."
+                    if [ $i == 10 ]; then
+                        echo -e "\nCould not create a connection, client might be offline"
+                    fi
+                    sleep 1
+                }
+            done
+            ssh -S ~/.anyshell/socket -O exit localhost
+        else
+            lsof -ti:41000 | xargs kill -9 &> /dev/null
+            ssh -f -N -T -M -S ~/.anyshell/socket $Server_user@$Server_dns -p 41999 -i ~/.ssh/anyshell-key -L 41000:localhost:$Host_port
+            for (( i = 0; i <= 10 ; i++ )); do
+                {
+                    ssh $Host_user@localhost -q -p 41000 && break 
+                } || { 
+                    echo -n "."
+                    if [ $i == 10 ]; then
+                        echo -e "\nCould not create a connection, client might be offline"
+                    fi
+                    sleep 1
+                }
+            done
+            ssh -S ~/.anyshell/socket -O exit localhost
+        fi
     else
-        lsof -ti:41000 | xargs kill -9 &> /dev/null
-        ssh -f -N -T -M -S ~/.anyshell/socket $Server_user@$Server_dns -p 41999 -i ~/.ssh/anyshell-key -L 41000:localhost:$Host_port
-        for (( i = 0; i <= 10 ; i++ )); do
-            {
-                ssh $Host_user@localhost -q -p 41000 && break 
-            } || { 
-                echo -n "."
-                if [ $i == 10 ]; then
-                    echo -e "\nCould not create a connection, client might be offline"
-                fi
-                sleep 1
-            }
-        done
-        ssh -S ~/.anyshell/socket -O exit localhost
+        echo -e "\nCommand:\n"
+        if [[ "$Host_public_IP" == "$Client_public_IP" ]]; then
+            echo "ssh $Host_user@$Host_local_IP"
+        elif [ "$Client_public_IP" == "$Server_public_IP" ]; then
+            lsof -ti:41000 | xargs kill -9 &> /dev/null
+            ssh -f -N -T -M -S ~/.anyshell/socket $Server_user@$Server_local_IP -p 41999 -i ~/.ssh/anyshell-key -L 41000:localhost:$Host_port
+            for (( i = 0; i <= 10 ; i++ )); do
+                {
+                    ssh $Host_user@localhost -q -p 41000 exit && echo -e "\nssh $Host_user@localhost -p 41000" && break
+                } || { 
+                    echo -n "."
+                    if [ $i == 10 ]; then
+                        echo -e "\nCould not create a connection, client might be offline"
+                    fi
+                    sleep 1
+                }
+            done
+        else
+            lsof -ti:41000 | xargs kill -9 &> /dev/null
+            ssh -f -N -T -M -S ~/.anyshell/socket $Server_user@$Server_dns -p 41999 -i ~/.ssh/anyshell-key -L 41000:localhost:$Host_port
+            for (( i = 0; i <= 10 ; i++ )); do
+                {
+                    ssh $Host_user@localhost -q -p 41000 exit && echo -e "\nssh $Host_user@localhost -p 41000" && break
+                } || { 
+                    echo -n "."
+                    if [ $i == 10 ]; then
+                        echo -e "\nCould not create a connection, client might be offline"
+                    fi
+                    sleep 1
+                }
+            done
+        fi
     fi
-
+    echo -e "\nPress \"ctrl+c\" to exit\n"
+    while true; do
+      :
+    done
     sed -i '4s/.*/0/' ~/.anyshell/hosts/$Host_name
     scp -P 41999 -i ~/.ssh/anyshell-key ~/.anyshell/hosts/$Host_name $Server_user@$Server_dns:/home/$Server_user/.anyshell/hosts/ >/dev/null
 
